spring:
  application:
    name: auth-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://${username}:${password}@localhost:9000

  jwt:
    secret: ${secret.key}
    token:
      access-expiration-time: 600000
      refresh-expiration-time: 1200000

  data:
    redis:
      host: localhost
      port: 6379

